name: Filemark Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'v*.*.* tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install upx
        run: sudo apt-get install -y upx

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: -f .goreleaser.yml release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
