name: Filemark Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'v*.*.* tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Make tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push --tags

      - name: Checkout tag
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.version }}

      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: ${{ github.event.inputs.version }}
          args: -f .goreleaser.yml release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
